const GET_REGIONS = "GET_REGIONS";
const SET_REGIONS = "SET_REGIONS";

const GET_POSTS = "GET_POSTS";
const SET_POSTS = "SET_POSTS";

const SET_FORM = "SET_FORM";

const GET_RESULT = "GET_RESULT";
const SET_RESULT = "SET_RESULT";

const SET_RESULT_COUNT = "SET_RESULT_COUNT";

const RESET_RESULTS = "RESET_RESULTS";

const SET_PDF_RESULT = "SET_PDF_RESULT";
export {
  GET_REGIONS,
  SET_REGIONS,
  GET_POSTS,
  SET_POSTS,
  SET_FORM,
  GET_RESULT,
  SET_RESULT,
  SET_RESULT_COUNT,
  RESET_RESULTS,
  SET_PDF_RESULT
};
